# Generated by Django 2.1.1 on 2019-05-20 09:31

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, null=True, verbose_name=django.contrib.auth.models.User)),
                ('Nombre', models.CharField(blank=True, max_length=200)),
                ('document', models.FileField(upload_to='documents/')),
                ('numb', models.IntegerField(null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
